apiVersion: skaffold/v1
kind: Config
metadata:
  name: tracetogether
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: trace-together # Your Docker image
      jib: {} # Just add this part for Jib
deploy:
  kustomize:
    path: k8s/overlays/gke # This could be anything, let's talk about this later
