apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-api.yaml
  - 99-ingress.yaml
# configMapGenerator:
#   - name: api-config
#     files:
#       - filename=conf/filename.conf

secretGenerator:
  - name: firebase-key
    files:
      - firebase-credentials.json=conf/firebase-credentials.json

configMapGenerator:
  - name: firebase-config
    files:
      - firebase-config.json=conf/firebase-config.json
